server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  application:
    name: ecom
  profiles:
    active: default
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    cassandra:
      schema-action: create-if-not-exists

astra:
  api:
    application-token: ${ASTRA_DB_APP_TOKEN}
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
    cross-region-failback: false
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
        request:
          timeout: 8s
          consistency: LOCAL_QUORUM
          page-size: 5000
      advanced:
        connection:
          init-query-timeout: 10s
          set-keyspace-timeout: 10s
        control-connection:
          timeout: 10s
